version: '2'
services:
  db:
    image: postgres:9.6.1-alpine
  cache:
    image: redis:3.2.5-alpine
  app:
    build: .
    command: bundle exec unicorn_rails -c config/unicorn.rb -E production
    depends_on:
      - db
      - cache
    environment:
      - VIRTUAL_HOST=*
      - VIRTUAL_HOST_WEIGHT=0
  cdn:
    image: nginx:1.10.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=*/assets/*
      - VIRTUAL_HOST_WEIGHT=1
  lb:
    image: dockercloud/haproxy:1.6.0
    links:
      - app
      - cdn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
