version: '2'
services:
  db:
    image: postgres
  cache:
    image: redis
  app:
    build: .
    command: bundle exec unicorn_rails -c config/unicorn.rb -E production
    depends_on:
      - db
      - cache
  web:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    volumes_from:
      - app
    depends_on:
      - app
